---

- hosts: all
  become: true
  remote_user: dmay
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
#    when: ansible_distribution in [ "Debian", "Ubuntu" ]

  - name: install vim-gtk3
    apt:
      name: vim-gtk3
      state: latest
# to remove, change to this
#      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: install build-essential
    apt:
      name: build-essential
      state: latest
# to remove, change to this
#      state: absent
    when: ansible_distribution == "Ubuntu"

...
